name: Publish VS-Code plugin

on: workflow_dispatch
                        
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
        
      - name: Get ballerina.vsix
        run: |
          npm install

          BALLERINA_VERSION="`jq -r '.version' _data/stable-latest/metadata.json`"
          curl http://dist-dev.ballerina.io/downloads/$BALLERINA_VERSION/ballerina-$BALLERINA_VERSION.vsix --output ballerina.vsix
             
      - name: Execute the VSCE commands
        uses: lannonbr/vsce-action@master
        with:
          args: publish -p $VSCE_TOKEN --packagePath ballerina.vsix
        env:
          VSCE_TOKEN: ${{ secrets.VSCODE_PAT }}
