name: Publish Intellij Plugin

on:
  push:
    branches:
      - prod-sync
    paths:
      - '_data/stable-latest/**'
    
jobs:
  publish_idea_plugin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
                  
    - name: Install jq for json manipulation
      run: sudo apt-get install jq

    - name: Clone ballerina-lang repo
      run: git clone https://github.com/ballerina-platform/ballerina-lang.git
          
    - name: Set oracle jdk, build and publish plugin
      run: |
        CURRENT_DIR=$PWD
        sudo apt-get install wget
        wget --header "Cookie: oraclelicense=accept-securebackup-cookie" https://javadl.oracle.com/webapps/download/GetFile/1.8.0_261-b12/a4634525489241b9a9e1aa73d9e118e6/linux-i586/jdk-8u261-linux-x64.tar.gz
        DWNLD_PATH=$PWD
        cd /usr/lib/jvm
        sudo rm -rfv /usr/lib/jvm/*
        sudo tar -xvzf $DWNLD_PATH/jdk-8u261-linux-x64.tar.gz
        JDK_PATH=$PWD
        echo 'export JAVA_HOME=$JDK_PATH/jdk1.8.0_261' >> ~/.bash_profile
        echo 'export PATH=$PATH:$JDK_PATH/jdk1.8.0_261/bin' >> ~/.bash_profile
        source ~/.bash_profile
        java -version
        echo $JAVA_HOME
        cd $CURRENT_DIR

        version="`jq -r '.version' _data/stable-latest/metadata.json`"
        BAL_VERSION="v${version}"

        cd ballerina-lang/tool-plugins/intellij/
        git checkout $BAL_VERSION
        ./gradlew buildPlugin 
        ./gradlew publishPlugin -PintellijPublishToken=${{ secrets.IDEA_TOKEN }}   
